FROM debian:jessie
# This dockerfile was inpired by greinacker/exim4

# create rootless user
RUN groupadd -g 1000 onetime && \
    useradd -m -d /var/lib/exim4 -s /bin/nologin -u 1000 -g 1000 onetime
  
# install packages: exim4, mailutils
RUN apt-get update \
 && apt-get -y --force-yes install rsync \
 && apt-get install --no-install-recommends -y --force-yes \
  exim4-daemon-light mailutils xtail vim \
 # Slim down image
 && apt-get clean \
 && chmod 777 /var/spool/exim4 \
 && ln -sf /dev/stdout /var/log/exim4/mainlog \
 && ln -sf /dev/stderr /var/log/exim4/panic \
 && ln -sf /dev/stderr /var/log/exim4/reject \
 && chmod 0755 /usr/sbin/exim4 \
 && usermod -a -G Debian-exim onetime

RUN set -ex \
  && mkdir -p /etc/exim4 /var/log/exim4 /var/run/exim4 /var/lib/exim4 \
  && chown onetime /var/log/exim4 /var/run/exim4 /var/lib/exim4 \
  && chown -R onetime /etc/exim4 

RUN ls -l /var/lib/exim4/config.autogenerated

# add the exim4 start script
ADD start.sh /exim_start
RUN chmod +x /exim_start


ENV EXIM_LOCALINTERFACE=0.0.0.0
ENV EXIM_ALLOWED_SENDERS=10.0.0.0/8:172.16.0.0/12:127.0.0.1:192.168.0.0/16

USER onetime

EXPOSE 25
ENTRYPOINT ["/exim_start"]
