apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exim4.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  EXIM_SMARTHOST: {{ default "localhost" .Values.secrets.EXIM_SMARTHOST | b64enc | quote }}
  EXIM_PASSWORD: {{ default "" .Values.secrets.EXIM_PASSWORD | b64enc | quote }}
  EXIM_ALLOWED_SENDERS: {{ default "*" .Values.secrets.EXIM_ALLOWED_SENDERS | b64enc | quote }}
  EXIM_MESSAGE_SIZE_LIMIT: {{ default "255M" .Values.secrets.EXIM_MESSAGE_SIZE_LIMIT | b64enc | quote }}
  EXIM_DOMAIN: {{ default "localhost" .Values.secrets.EXIM_DOMAIN | b64enc | quote }}
